title: Мы можем
item1:
  src: images/products/1.png
  title: Провести индивидуальную или групповую фотосъемку
item2:
  src: images/products/2.png
  title: Подобрать идеальный образ для фотосессий
item3:
  src: images/products/3.png
  title: Подобрать локацию для съемок
item4:
  src: images/products/4.png
  title: Организовать видеосъемку с возможностью создания Reels
item5:
  src: images/products/5.png
  title: Профессионально обработать ваши фото и видео
item6:
  src: images/products/5.png
  title: Профессионально обработать ваши фото и видео
item7:
  src: images/products/5.png
  title: Профессионально обработать ваши фото и видео
item8:
  src: images/products/5.png
  title: Профессионально обработать ваши фото и видео
item9:
  src: images/products/5.png
  title: Профессионально обработать ваши фото и видео
item10:
  src: images/products/5.png
  title: Профессионально обработать ваши фото и видео
item11:
  src:
  title:
